<?php


namespace app\common\controller;

use app\admin\model\Admin;
use think\facade\Session;
use think\facade\View;

class AdminController extends \app\BaseController
{
    protected $middleware = [\app\admin\middleware\Check::class];

    protected $view = null;

    protected $model = null;

    protected $userInfo = null;

    protected $userType = 'admin';

    protected $returnData = [];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->returnData = [
            'code' => 0,
            'msg' => lang('Unknown error'),
            'data' => []
        ];

        $this->view = View::instance();
//        $this->view->engine()->layout('layout');
        $token = $this->request->cookie('hbcall_admin_token');
        if ($token) {
            $this->userInfo = Admin::where('token', $token)->find();
        }
        $this->view->assign('user', $this->userInfo);
    }

}
