<?php


namespace app\common\controller;

use think\facade\Session;
use app\common\model\User as UserModel;
use app\company\model\Company as CompanyModel;
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Parser;
use Lcobucci\JWT\Validation;

class ApiController extends \app\BaseController
{
    protected $noNeedLogin = ['login'];

    protected $userInfo = null;

    protected $userType = 'user';

    protected $UserModel = null;

    protected $CompanyModel = null;

    protected $model = null;

    protected $returnData = [
        'code' => 0,
        'msg' => '未知错误',
        'data' => [],
//        'sub_code' => 'unknow error',
//        'sub_msg' => '系统繁忙',
    ];

    protected static $jwt_config = [
        'audience' => 'http://caller.hbosw.com', // 接收人
        'id' => 'ww8ee3085852a83f1d',
        'sign' => 'UbHJAz3LqCQ71Efq0PadywjTG2Cq13nb',
        'issuer' => 'http://caller.hbosw.com',
        'expire' => 3600 * 24 * 7
    ];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->UserModel = UserModel::class;

        $this->CompanyModel = CompanyModel::class;

        $this->userType = $this->request->param('userType', 'user');

        if (!$this->userType) {
            $this->returnData['msg'] = '未提供正确的参数：userType';
            exit(json_encode($this->returnData));
        }

        $userId = Session::get('api_' . $this->userType . '.id');
        if ($this->userType === 'user') {
            $this->userInfo = UserModel::with(['company', 'userXnumber' => ['numberStore']])->find($userId);
        } else if ($this->userType === 'company') {
            $this->userInfo = CompanyModel::with(['user'])->find($userId);
        }
    }

    protected function getUserInfo()
    {
        return Session::get('api_' . $this->userType, null);
    }

    protected function isLogin()
    {
        return Session::has('api_' . $this->userType);
    }

    public static function getToken($user_id)
    {

    }

}
