<?php


namespace app\common\controller;

use think\facade\Session;
use think\facade\View;

class ApiController extends \app\BaseController
{
    protected $returnData = [
        'code' => 0,
        'msg' => '未知错误',
        'data' => [],
//        'sub_code' => 'unknow error',
//        'sub_msg' => '系统繁忙',
    ];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected function getUserInfo()
    {
        return Session::get('api_user', null);
    }

    protected function isLogin()
    {
        return Session::has('api_user');
    }
}
