<?php


namespace app\common\controller;

use app\company\model\Company;
use think\facade\Session;
use think\facade\View;
use app\common\traits\CompanyTrait;

class CompanyController extends \app\BaseController
{
    use CompanyTrait;

    protected $middleware = [\app\company\middleware\Check::class];

    protected $userType = 'company';

    protected $view = null;

    protected $model = null;

    protected $userInfo = null;

    protected $token = null;

    protected $noNeedLogin = ['login'];

    protected $returnData = [
        'code' => 0,
        'msg' => '未知错误',
        'data' => []
    ];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->view = View::instance();
        $this->token = $this->request->cookie('hbcall_company_token');
        if (!$this->token) {
            $this->userInfo = Company::withCount('user')
                ->with(['companyXnumber' => ['numberStore']])
                ->where('token', $this->token)
                ->find();
        }
        $this->view->assign('user', $this->userInfo);
    }

    public function delSession()
    {
        Session::delete('company');
    }
}
