<?php


namespace app\common\controller;

use think\facade\Session;
use think\facade\View;

class CompanyController extends \app\BaseController
{
    protected $middleware = [\app\company\middleware\Check::class];

    protected $view = null;

    protected $model = null;

    protected $userInfo = null;

    protected $returnData = [
        'code' => 0,
        'msg' => '未知错误',
        'data' => []
    ];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->view = View::instance();
//        $this->view->engine()->layout('layout');
        $this->userInfo = Session::get('company');
        $this->view->assign('user', $this->userInfo);
    }

}
