<?php


namespace app\common\controller;

use think\facade\View;

class HomeController extends \app\BaseController
{
    protected $view = null;

    // 小号
    protected $axb_number = '18426190532';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->view = View::instance();
//        $this->view->engine()->layout('layout');
    }

}
