<?php

namespace app\admin\controller;

use app\common\controller\AdminController;
use app\admin\model\admin;
use app\common\model\CallHistory;
use app\company\model\Company;
use arron\Random;
use think\facade\Db;
use think\facade\Session;
use app\common\model\Expense;

class Index extends AdminController
{
    protected $lang = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->lang = [
            'totalCallHistory' => '总记录',
            'totalGtZero' => '接听数',
            'totalGtSixty' => '大于1分钟',
            'totalBetweenZeroAndSixty' => '1分钟内',
            'totalBetweenOneToThree' => '1-3分钟',
            'totalBetweenThreeToFive' => '3-5分钟内',
            'totalGtFive' => '大于5分钟',
            'totalEqZero' => '未接听',
        ];
    }

    public function index()
    {
        return $this->view->fetch();
    }

    public function dashboard()
    {
        $this->view->assign(getCosts());

        return $this->view->fetch();
    }

    public function getReport()
    {
        if ($this->request->isPost()) {
            $result['totalCallHistory'] = CallHistory::count();
            $result['totalCallAndPickUp'] = CallHistory::where('call_duration', '>', 0)->count();
            $result['totalCallAndNoPickUp'] = CallHistory::where('call_duration', '=', 0)->count();
            $result['totalCallDuration'] = Expense::sum('duration');
            $result['chartData'] = [
                [
                    'name' => $this->lang['totalBetweenZeroAndSixty'],
                    'value' => CallHistory::whereBetween('call_duration', [1, 60])->count()
                ],
                [
                    'name' => $this->lang['totalBetweenOneToThree'],
                    'value' => CallHistory::whereBetween('call_duration', [61, 180])->count()
                ],
                [
                    'name' => $this->lang['totalBetweenThreeToFive'],
                    'value' => CallHistory::whereBetween('call_duration', [181, 300])->count()
                ],
                [
                    'name' => $this->lang['totalGtFive'],
                    'value' => CallHistory::where('call_duration', '>', 300)->count()
                ]
            ];
            $this->returnData['code'] = 1;
            $this->returnData['data'] = $result;
            $this->returnData['msg'] = 'success';
            return json($this->returnData);
        }

        return json($this->returnData);
    }

    public function getTopList()
    {
        if ($this->request->isPost()) {
            $result = Company::withCount(['callHistory' => function ($query, &$alias) {
                $query->where('call_duration', '>', 0);
                $alias = 'callHistory_pickup_count';
            }])
                ->withCount(['callHistory' => function ($query, &$alias) {
                    $query->where('call_duration', '=', 0);
                    $alias = 'callHistory_count';
                }])
                ->withSum('expense', 'cost')
                ->withSum(['expense' => 'duration_sum'], 'duration')
                ->order('callHistory_count', 'desc')
                ->limit(5)
                ->select();
            $this->returnData['code'] = 1;
            $this->returnData['data'] = $result;
            $this->returnData['msg'] = 'success';
            return json($this->returnData);
        }
        return json($this->returnData);
    }

    public function getCallList()
    {
        if ($this->request->isPost()) {

            return json($this->returnData);
        }

        return json($this->returnData);
    }

    public function login()
    {
        /*$salt = getRandChar(6);
        $pwd = getEncryptPassword('123456', $salt);
        dump($salt);
        dump($pwd);*/
        if (Session::has('admin')) {
            return redirect(url('/index'));
        }

        if ($this->request->isPost()) {
            /*$check = $this->request->checkToken('__token__');
            if(false === $check) {
                $token = $this->request->buildToken();
                return json(['data' => ['token' => $token], 'msg' => lang('Invalid token') . '，请重新提交', 'code' => 0]);
            }*/

            $param = $this->request->param();
            $user = Admin::getByUsername($param['username']);
            if (!$user) {
                return json(['data' => [], 'msg' => lang('Account is incorrect'), 'code' => 0]);
            }

            if (!$user->getData('status')) {
                return json(['data' => [], 'msg' => lang('Account is locked'), 'code' => 0]);
            }

            $password = getEncryptPassword($param['password'], $user->salt);
            if ($password !== $user->password) {
                return json(['data' => [], 'msg' => lang('Password is incorrect'), 'code' => 0]);
            }

            if (!captcha_check($param['captcha'])) {
                return json(['data' => [], 'msg' => lang('Captcha is incorrect'), 'code' => 0]);
            }

            $user->prevtime = $user->getData('logintime');
            $user->logintime = time();
            $user->loginip = $this->request->ip();

            $user->save();

            Session::set('admin', $user->toArray());

            return json(['data' => [], 'msg' => lang('Logined'), 'code' => 1, 'url' => (string)url('/index')]);
        }
        return $this->view->fetch();
    }

    public function logout()
    {
        Session::delete('admin');
        return redirect((string)url('/index/login'));
    }

}
