<?php

namespace app\api\controller;

use app\common\controller\ApiController;
use app\common\library\Aes;
use app\common\model\Expense;
use think\facade\Session;
use app\common\traits\UserTrait;

class User extends ApiController
{
    use UserTrait;

    protected $token_expire_time = 3600 * 24 * 7;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//        dump($this->getUserInfo());
//        dump($this->isLogin());

        $sessionId = Session::getId();
        // dump($this->uuid());
//        dump('session_id: ' . $sessionId);
        $token1 = hash_hmac('haval256,3', $this->uuid(), substr($sessionId, 0, 22));
        $token2 = hash_hmac('ripemd320', $this->uuid(), substr($sessionId, 0, 22));
//        dump('token1: ' . $token1);
//        dump('token2: ' . $token2);
        $server = $this->request->server();
//        dump($this->request->header());
//        dump($this->request->post());

        $uuid = sha1(md5(uniqid(md5(microtime(true)), true)));
        $password = sha1(sha1('hbcall_') . md5('123456') . md5('_encrypt') . sha1('123456'));
        $crypt = md5(crypt('QQX@lyq20151111', 'L9uSPt'));
        $openssl_decrypt = openssl_decrypt('AQShHlFSuUgljo1qDsBjjk4JA8rfARy9jnKULFTO2crpruQ7UgHUoT1qBob49OMmUycWcCbk4/j6guxfA1nyjlMvST67CHEuVdaNtfIvL4Tz/+3nqLtJJR4Hj/HXbVKlj3hyZ2AEhuKjPpHjhbogTeUsTkCeEzgx6X3uKAtQZcKOaOYD/BAzHEGqd2lrNBPD2GmAt1p1qFTOl27abiIKBA4usL2GRVmKHy3bhpsO9CFYGYW//Q2GXbS8iY/rJCluX64m+G2O+wLMQoWKNfB0NhoGynx8jMFR53T3NliJ74CkqSrknNxcdYelUCvwxBIDk3SLmABZ6FFJr/gVqB2phEQWOOvogjD2FEa5DBe2aEafcpsmoVt5bXx1yIyqJGEoNiY+Dq1MU5benP01NmxOhKNs6dLN137Phs9SIHlDJMVBBM77rqm+fHwwWtOgYsUpKw3rW6a1VwMvrCBy9cpvqVmfPRjJmqbeJIjldbE/0ibDxlGOj7cqxIe9D4QwfNpja8VxMAVDcPiXRL7IcOjwGZVzDe99UUZum0DDI2rCvzM=', 'AES-128-ECB', '$2y$10$z9Y0yMaiEmoSQ71m70JGyehZle1zHgboB9yEDOQUobhNzErotnRWe');
//        echo json_encode($this->getUserInfo(), true);
//        return json($openssl_decrypt);
        $config = [
            'key' => 'UbHJAz3LqCQ71Efq0PadywjTG2Cq13nb',
            'iv' => substr(md5('UbHJAz3LqCQ71Efq0PadywjTG2Cq13nb'), 0, 16),
            'method' => 'AES-128-CBC'
        ];
        $aes = new Aes($config);
        $encode = json_encode($this->getUserInfo(), JSON_UNESCAPED_UNICODE);
        $data = $aes->aesEn($encode);
        $deData = $aes->aesDe('lFzJrxqaQle6gIcD/1Jh4LWMwblh7/Jzwv1ylTyw+LCUd3GSETsnHAqgJFzhjWTTth4W/HgcMtNGYhkGwXzVRnrTRdNNDuX4Etf94mS0Ex8aicPJSFUfhBRuCjdA1SIqbyy3V1CZsM1Sk/vARi1CD7hoHTYlnLus6tP1Wg83zLBZ2pzOgv0iF19OWY0f1BmK5nrkhMfPVBNR2t8GemYiPgTTMlb3rQ87GM7b3xgg4R4t+S2iVrG5yex1dc7qqWjMJZnonIVZKkIXFdo46NrpAe/Z94t+VZpKkxewLyxzCCAkZnyKgwfZcIE+4D2kC6mX+1zU5MANZRLzNktPFsr8OBBB7mvJ8x1PvABwLtapNHDaqoVrwJLdLC3pgtNXfozM/RZVLUA5hw46zYM+IKs8IiRH4wQOazU4A62CcThiBxvuk8ONE67SDUl9aIFmOI6coJjIemgjlumPYINQ/z6Fe33ShScGOnvld25yAT4SdaEjQ0oI9kdtl9146r7xYwmwT2GMFCQ1gHuoEec1CSrJa7g90a3Bj1Dc40ggzMpQNjhg1MRA68CM/l7cwJAdwPyQ9oKyhrs8gN2eqqYioTzzO4nxszBLhxjUvqwrhIhTX7+XPa2f682umZCf+aRs37p0zJhB9hpmNR07o8RbemVp7dFrGr4Mb85ztTRbQOBU9lf9miNZrgoLs1qHQEZyBa32x2xVPa4+U0LaZlHt9gP0f0X1jiXfbuQwTjxwYWL3p7U=');
        $deData = json_decode($deData, JSON_UNESCAPED_UNICODE);
        return json([
            'code' => 1,
            'data' => [
//                'session_id' => $sessionId,
//                'header' => $this->request->header(),
//                'session' => $sessionId,
//                'device' => $this->agent->device() ?: '',
//                'platform' => $this->agent->platform() ?: '',
//                'browser' => $this->agent->browser() ?: '',
//                'platformVersion' => $this->agent->version($this->agent->platform()) ?: '',
//                'browserVersion' => $this->agent->version($this->agent->browser()) ?: '',
//                'uuid' => $uuid,
//                'uuid2' => strlen($uuid),
//                'uuid3' => password_hash('123456', PASSWORD_BCRYPT),
//                'token' => $password,
//                'password' => getEncryptPassword('123456'),
//                'password_hash' => password_hash('123456' . '_hbcall', PASSWORD_DEFAULT),
//                'password_verify' => password_verify('123456' . '_hbcall', '$2y$10$z9Y0yMaiEmoSQ71m70JGyehZle1zHgboB9yEDOQUobhNzErotnRWe'),
//                'thinkphp_token' => request()->buildToken(),
//                'crypt' => password_get_info('$2y$10$wV9EfCKJFnf61G4B6iWhde6OQazaV5vfldRNpAmFUaqdWswxUlqFi'),
                'openssl_config' => $config,
                'openssl_encrypt' => $aes->aesEn($encode),
                'openssl_decrypt' => $openssl_decrypt,
                'openssl_decrypt_json' => $deData,
            ],
            'msg' => '请求成功'
        ]);
    }

    /**
     * 获取全球唯一标识
     * @return string
     */
    public function uuid()
    {
        return sprintf(
            '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0x0fff) | 0x4000,
            mt_rand(0, 0x3fff) | 0x8000,
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff)
        );
    }

    public function login()
    {
        if ($this->request->isPost()) {
            $param = $this->request->param();

            if (!isset($param['username']) || trim($param['username']) === '') {
                $this->returnData['msg'] = '参数错误：缺少 username';
                return json($this->returnData);
            }

            if (!isset($param['password']) || trim($param['password']) === '') {
                $this->returnData['msg'] = '参数错误：缺少 password';
                return json($this->returnData);
            }

            $model = ucfirst($this->userType) . 'Model';
            $user = $this->$model::where('username', $param['username'])
                ->find();

            if (!$user) {
                $this->returnData['msg'] = lang('Account is incorrect');
                return json($this->returnData);
            }

            if (!$user->getData('status')) {
                $this->returnData['msg'] = lang('Account is locked');
                return json($this->returnData);
            }

            $password = getEncryptPassword($param['password'], $user->salt);
            if ($password !== $user->password) {
                $this->returnData['msg'] = lang('Password is incorrect');
                return json($this->returnData);
            }

            $now = time();
            $user->prevtime = $user->getData('logintime');
            $user->logintime = $now;
            $user->loginip = $this->request->ip();
            $user->token = createToken($password);
            $user->token_expire_time = $now + $this->token_expire_time;
            $user->platform = $this->agent->platform();
            $user->platform_version = $this->agent->version($this->agent->platform());
            $user->browser = $this->agent->browser();
            $user->browser_version = $this->agent->version($this->agent->browser());
            $user->device = $this->agent->device();
            $user->save();

            $where = [$this->userType . '_id' => $user->id];
            $user->yesterday_duration = Expense::where($where)
                ->whereRaw("date_format(date_sub(now(), interval 1 day), '%Y-%m-%d') = from_unixtime(createtime, '%Y-%m-%d')")
                ->sum('duration');
            $user->today_duration = Expense::where($where)
                ->whereRaw("date_format(now(), '%Y-%m-%d') = from_unixtime(createtime, '%Y-%m-%d')")
                ->sum('duration');

            Session::set('api_' . $this->userType, $user->toArray());

            $this->returnData['code'] = 1;
            $this->returnData['msg'] = lang('logined');
            $this->returnData['data'] = $user->hidden(['password', 'salt'])->toArray();

            return json($this->returnData);
        }

        return json($this->returnData);
    }

    public function getUserProfile()
    {
        return json($this->getUserInfo());
    }

    public function checkLogin()
    {
        $this->returnData['code'] = 1;
        $this->returnData['msg'] = 'Success';
        $this->returnData['data'] = [
            'login' => $this->isLogin(),
        ];

        return json($this->returnData);
    }

    public function logout()
    {
        Session::delete('api_' . $this->userType);
        $this->userInfo->token = '';
        $this->userInfo->token_expire_time = 0;
        $this->userInfo->save();
        $this->returnData['code'] = 1;
        $this->returnData['msg'] = '退出成功';
        return json($this->returnData);
    }
}
